// <auto-generated />
using E_Recrutement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Recrutement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Recrutement.Models.Candidat", b =>
                {
                    b.Property<int>("IdCandidat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCandidat"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diplome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreAnneeExperience")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCandidat");

                    b.ToTable("Candidats");
                });

            modelBuilder.Entity("E_Recrutement.Models.Offres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdRecruteur")
                        .HasColumnType("int");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Remuneration")
                        .HasColumnType("int");

                    b.Property<string>("Secteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdRecruteur = 101,
                            Poste = "Développeur Full Stack",
                            Profil = "Ingénieur",
                            Remuneration = 20000,
                            Secteur = "Développement logiciel",
                            TypeContrat = "CDI"
                        },
                        new
                        {
                            Id = 2,
                            IdRecruteur = 102,
                            Poste = "Data Analyst",
                            Profil = "Master",
                            Remuneration = 15000,
                            Secteur = "Analyse de données",
                            TypeContrat = "CDD"
                        },
                        new
                        {
                            Id = 3,
                            IdRecruteur = 103,
                            Poste = "Spécialiste en Sécurité Informatique",
                            Profil = "Ingénieur",
                            Remuneration = 18000,
                            Secteur = "Cybersécurité",
                            TypeContrat = "CDI"
                        },
                        new
                        {
                            Id = 4,
                            IdRecruteur = 104,
                            Poste = "Développeur Mobile",
                            Profil = "Licence",
                            Remuneration = 12000,
                            Secteur = "Développement mobile",
                            TypeContrat = "Freelance"
                        },
                        new
                        {
                            Id = 5,
                            IdRecruteur = 105,
                            Poste = "Chef de Projet IT",
                            Profil = "Master",
                            Remuneration = 25000,
                            Secteur = "Gestion de projets IT",
                            TypeContrat = "CDI"
                        });
                });

            modelBuilder.Entity("E_Recrutement.Models.Recruteur", b =>
                {
                    b.Property<int>("IdRecruteur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecruteur"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRecruteur");

                    b.ToTable("Recruteurs");
                });
#pragma warning restore 612, 618
        }
    }
}
